In [1]:
from pyspark.sql import SparkSession
from pyspark.sql import Row
from delta import *
from os import PathLike
from hdfs import InsecureClient
from pyspark.sql.types import LongType, StringType, StructField, StructType, BooleanType, ArrayType, IntegerType
from pyspark.sql.functions import when, col, concat, lit, substring, avg, sum, count, countDistinct

# warehouse_location points to the default location for managed databases and tables
warehouse_location = 'hdfs://hdfs-nn:9000/AreasVerdes/warehouse'

builder = SparkSession \
    .builder \
    .master("local[2]") \
    .appName("Python Spark DataFrames and SQL") \
    .config("spark.sql.warehouse.dir", warehouse_location) \
    .config("hive.metastore.uris", "thrift://hive-metastore:9083") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .config("spark.jars.packages", "io.delta:delta-core_2.12:1.0.0") \
    .enableHiveSupport() \

spark = configure_spark_with_delta_pip(builder).getOrCreate()

In [2]:
goldPot = spark.table("AreasVerdes.Potencial_Table")

In [3]:
goldPot = goldPot.select("Data_Created","Borough","Block","Lot","Address","Parcel_Name", "Agency", "Total_Area", "Community_Board", "Council_District", "Coordinates", "Potencial_Urban_Ag", "Latitude", "Longitude", "BIN", "NTA")

In [4]:
goldPot.toPandas()

,Data_Created,Borough,Block,Lot,Address,Parcel_Name,Agency,Total_Area,Community_Board,Council_District,Coordinates,Potencial_Urban_Ag,Latitude,Longitude,BIN,NTA
0,11/02/2017 12:00:00 AM,Queens,3916,35,5 AVENUE,None,DCAS,15000,407,19.0,0/0,Least Potencial,None,None,None,None
1,11/02/2017 12:00:00 AM,Queens,6391,24,63 ROAD,None,DCAS,4700,407,24.0,0/0,Least Potencial,None,None,None,None
2,11/02/2017 12:00:00 AM,Queens,14246,1189,DAVENPORT COURT,HAMILTON BEACH FIRE DEPT ACCES,DCAS,3200,410,32.0,0/0,Least Potencial,None,None,None,None
3,11/02/2017 12:00:00 AM,Queens,14254,1640,104 STREET,HAMILTON BEACH,DCAS,1600,410,32.0,0/0,Least Potencial,None,None,None,None
4,11/02/2017 12:00:00 AM,Queens,15622,78,BEACH 13 STREET,None,DCAS,3400,414,31.0,0/0,Least Potencial,None,None,None,None
5,11/02/2017 12:00:00 AM,Queens,15622,180,NEW HAVEN AVENUE,None,DCAS,4057,414,31.0,0/0,Least Potencial,None,None,None,None
6,11/02/2017 12:00:00 AM,Staten Island,5687,130,ARTHUR KILL ROAD,None,DCAS,35206,503,51.0,0/0,Least Potencial,None,None,None,None
7,11/02/2017 12:00:00 AM,Queens,14228,62,102 STREET,None,DCAS,100128,410,32.0,0/0,Least Potencial,None,None,None,None
8,11/02/2017 12:00:00 AM,Bronx,2875,67,PLIMPTON AVENUE,CROSS BX EXPWY-SEC-1,DOT,2573,205,14.0,0/0,Most Potential,None,None,None,None
9,11/02/2017 12:00:00 AM,Brooklyn,7074,1,1528 SURF AVENUE,CONEY ISLAND EAST,DOT,7469,313,47.0,988935/148775,Least Potencial,11224,None,None,3000000
10,11/02/2017 12:00:00 AM,Queens,15953,47,BEACH 36 STREET,"EDGEMERE URA, SITE #41",DOT,5400,414,31.0,0/0,Least Potencial,None,None,None,None
11,11/02/2017 12:00:00 AM,Queens,15954,56,BEACH 37 STREET,"EDGEMERE URA, SITE #43",DOT,4000,414,31.0,0/0,Least Potencial,None,None,None,None
12,11/02/2017 12:00:00 AM,Staten Island,370,200,MANOR ROAD,GOODELL AVE,DOT,13629,501,50.0,0/0,Least Potencial,None,None,None,None
13,11/02/2017 12:00:00 AM,Staten Island,691,1,FINE BOULEVARD,MAPPED RICHMOND PARKWAY,DOT,15820,502,NaN,0/0,Least Potencial,None,None,None,None
14,11/02/2017 12:00:00 AM,Queens,15952,13,BEACH 36 STREET,GREENTHUMB COMMUNITY GARDEN,PARKS,3067,414,31.0,0/0,Most Potential,None,None,None,None
15,11/02/2017 12:00:00 AM,Staten Island,6353,42,BAYVIEW TERRACE,BAYVIEW TERRACE PARK,PARKS,14400,503,51.0,0/0,Least Potencial,None,None,None,None
16,11/02/2017 12:00:00 AM,Brooklyn,1538,43,45 SOMERS STREET,LOTS FOR TOTS,ACS;HPD,6800,316,41.0,1008754/186644,Least Potencial,11233,None,None,3000000
17,11/02/2017 12:00:00 AM,Bronx,2403,31,MELROSE AVENUE,None,HPD,2878,201,17.0,0/0,Most Potential,None,None,None,None
18,11/02/2017 12:00:00 AM,Bronx,2403,37,387 EAST 156 STREET,None,HPD,2646,201,17.0,1007535/238440,Most Potential,10455,None,None,2000000
19,11/02/2017 12:00:00 AM,Brooklyn,3590,40,RIVERDALE AVENUE,None,HPD,2500,316,42.0,1009832/180243,Most Potential,None,None,None,None
20,11/02/2017 12:00:00 AM,Queens,15960,43,480 BEACH 43 STREET,"EDGEMERE URA, SITE #52",HPD,7600,414,31.0,1046795/157272,Most Potential,11691,None,None,4000000
21,11/02/2017 12:00:00 AM,Queens,15960,46,BEACH 43 STREET,"EDGEMERE URA, SITE #52",HPD,4000,414,31.0,0/0,Most Potential,None,None,None,None
22,11/02/2017 12:00:00 AM,Queens,15960,48,BEACH 43 STREET,"EDGEMERE URA, SITE #52",HPD,2850,414,31.0,0/0,Most Potential,None,None,None,None
23,11/02/2017 12:00:00 AM,Queens,15961,61,518 BEACH 43 STREET,"EDGEMERE URA, SITE #51",HPD,3034,414,31.0,1046760/157646,Most Potential,11691,None,None,4000000
24,11/02/2017 12:00:00 AM,Queens,15961,63,BEACH 43 STREET,"EDGEMERE URA, SITE #51",HPD,10450,414,31.0,0/0,Most Potential,None,None,None,None
25,11/02/2017 12:00:00 AM,Queens,15962,19,BEACH 44 STREET,"EDGEMERE URA, (P/O 58 & 59)",HPD,14824,414,31.0,0/0,Most Potential,None,None,None,None
26,11/02/2017 12:00:00 AM,Queens,15962,28,574 BEACH 44 STREET,"EDGEMERE URA, SITE #58",HPD,3823,414,31.0,0/0,Most Potential,11691,None,None,None
27,11/02/2017 12:00:00 AM,Queens,15962,30,BEACH 44 STREET,None,HPD,5704,414,31.0,0/0,Most Potential,None,None,None,None
28,11/02/2017 12:00:00 AM,Queens,15962,33,BEACH 44 STREET,None,HPD,8187,414,31.0,0/0,Most Potential,None,None,None,None

In [5]:
potential = goldPot \
    .groupBy("Borough", "Potencial_Urban_Ag") \
    .agg(
        count(goldPot.Potencial_Urban_Ag).alias("Potencial"),
        avg(goldPot.Total_Area).alias("Total_Area")
    )

potential= potential.withColumn("Potencial",col("Potencial").cast(IntegerType())) 
potential= potential.withColumn("Total_Area",col("Total_Area").cast(IntegerType())) 
potential.toPandas()

         Borough Potencial_Urban_Ag  Potencial  Total_Area
0       Brooklyn     Most Potential          1        2500
1         Queens    Least Potencial          9       15720
2          Bronx     Most Potential          3        2699
3         Queens     Most Potential         10        6353
4  Staten Island    Least Potencial          4       19763
5       Brooklyn    Least Potencial          2        7134

In [6]:
potential \
    .select("Borough", "Potencial_Urban_Ag", "Potencial", "Total_Area") \
    .write \
    .mode("overwrite") \
    .format("delta") \
    .save("hdfs://hdfs-nn:9000/AreasVerdes/gold/potential")